<?php

namespace App\Http\Controllers;

use App\Http\Requests\CreateEnvioNotaServicoRequest;
use App\Http\Requests\UpdateEnvioNotaServicoRequest;
use App\Repositories\EnvioNotaServicoRepository;
use App\Http\Controllers\AppBaseController;
use Illuminate\Http\Request;
use Flash;
use GuzzleHttp\Client;
use Response;

class EnvioNotaServicoController extends AppBaseController
{
    /** @var  EnvioNotaServicoRepository */
    private $envioNotaServicoRepository;

    public function __construct(EnvioNotaServicoRepository $envioNotaServicoRepo)
    {
        $this->envioNotaServicoRepository = $envioNotaServicoRepo;
    }

    /**
     * Display a listing of the EnvioNotaServico.
     *
     * @param Request $request
     *
     * @return Response
     */
    public function index(Request $request)
    {
        $envioNotaServicos = $this->envioNotaServicoRepository->all();

        return view('envio_nota_servicos.index')
            ->with('envioNotaServicos', $envioNotaServicos);
    }

    /**
     * Show the form for creating a new EnvioNotaServico.
     *
     * @return Response
     */
    public function create()
    {
        return view('envio_nota_servicos.create');
    }
    /*protected function getRestClientUtil()
    {
        $curl =  curl_init();

        return RestClient::newInstance()->addHeaders([
            "Content-Type: application/json",
        ]);
    }
    protected function getRestClient()
    {
        $restClient = getRestClientUtil();
        $headers[] = "client_id:" ."7ef1d710-35c2-3aa1-82f8-6b82dc1b58d4";


        return $restClient;
    }
    private function grantCode()
    {
        $curl =  curl_init();
        $restClient = $this->getRestClient();

        $data = [
            'client_id' => "7ef1d710-35c2-3aa1-82f8-6b82dc1b58d4",
            'redirect_uri' => "http://3.22.8.104:8082"
        ];
        $dataJson = json_encode($data);
        $retorno = $restClient->sendPost("https://api-energisa.sensedia.com/oauth/", $dataJson);

        if (!empty($retorno->error)) {
           dd($retorno->error);
        }

        return $retorno;
    }
    private function validarExisteValor($value): void
    {
        if (empty($value)) {
            throw new NegocioException(Message::MSG_FALHA_AUTENTICACAO_ENERGISA);
        }
    }
    private function authEnergiza($accessTokenParam = null)
    {
        $grantCode = $this->grantCode();
        $this->validarExisteValor($grantCode);
        $grantCode = json_decode($grantCode);

        $this->validarExisteValor($grantCode->redirect_uri);
        $codeArray = explode("code=", $grantCode->redirect_uri);
        $accessToken = $this->accessToken($codeArray[1]);

        $this->validarExisteValor($accessToken);
        $accessToken = json_decode($accessToken);

        $this->validarExisteValor($accessToken->access_token);
        $restClient = $this->getRestClient();

        if (empty($accessTokenParam)) {
            $restClient->addHeader("access_token:" . $accessToken->access_token);
        }else{
            $restClient->addHeader("access_token:" . $accessTokenParam);
        }
        return $restClient;
    }
    public function enviarArquivoXml($base64, $mensagemNota = null, $isErro = "N")
    {
        $restClient = new RestClient();

        $restClient = $this->authEnergiza();

        $astrEnergisaXmlTo = new AstrEnergisaXmlTO();
        $astrEnergisaXmlTo->setXmlBase64($base64);
        $astrEnergisaXmlTo->setExtensaoArquivo(self::EXTENSAO_ARQUIVO);
        $astrEnergisaXmlTo->setArquivoEletronico(self::ARQUIVO_ELETRONICO);
        $astrEnergisaXmlTo->setMensagemNota($mensagemNota);
        $astrEnergisaXmlTo->setErroNota($isErro);

        $dataJson = JsonUtils::toJson($astrEnergisaXmlTo);

        return $restClient->sendPost(AppConfig::getUrlEnergisa('of_recebe_xml'), $dataJson);
    }*/
    /**
     * Store a newly created EnvioNotaServico in storage.
     *
     * @param CreateEnvioNotaServicoRequest $request
     *
     * @return Response
     */
    public function authEnergisa()
    {
        $curl = curl_init();

        curl_setopt_array($curl, array(
          CURLOPT_URL => "api-energisa.sensedia.com/oauth/grant-code",
          CURLOPT_RETURNTRANSFER => true,
          CURLOPT_ENCODING => "",
          CURLOPT_MAXREDIRS => 10,
          CURLOPT_TIMEOUT => 0,
          CURLOPT_FOLLOWLOCATION => true,
          CURLOPT_HTTP_VERSION => CURL_HTTP_VERSION_1_1,
          CURLOPT_CUSTOMREQUEST => "POST",
          CURLOPT_POSTFIELDS =>"{\r\n \"redirect_uri\" : \"http://localhost:8000/\",\r\n \"client_id\" : \"7ef1d710-35c2-3aa1-82f8-6b82dc1b58d4\"\r\n}",
          CURLOPT_HTTPHEADER => array(
            "Content-Type: application/json"
          ),
        ));

        $response = curl_exec($curl);
        curl_close($curl);
        $tokenAux = explode("http://localhost:8000/?code=", $response);
        if($tokenAux == 0)
        {
            return "error authentication";
        }
        $tokenF=explode('"}',$tokenAux[1]);
        $token = $tokenF[0];
        return $token;
    }
    public function store(CreateEnvioNotaServicoRequest $request)
    {
        $input = $request->all();
        // salvando no storage
        $file = $input['arquivo'];
        $fileExtension = $file->getClientOriginalExtension();
        $fileName = $input['identificador_nota']. ".".$fileExtension;
        $destinationPath = $input['estabelecimento'] . "/". $fileName;
        \Storage::disk('local')->put($destinationPath,file_get_contents($file->getRealPath()));
        // fim do salvamento no storage
        $input['identificador_nota']= $input['identificador_nota'];
        $input['path_arquivo']=$destinationPath;
        $envioNotaServico = $this->envioNotaServicoRepository->create($input);
        $token = $this->authEnergisa();
        if($token == "error authentication")
        {
            Flash::error('Erro ao enviar o XML');
            return redirect(route('envioNotaServicos.index'));
        }
       /* $curl = curl_init();

        curl_setopt_array($curl, array(
        CURLOPT_URL => "http://hml-api.energisa.io/WSCFSPB_SFC/v1/of_recebe_xml",
        CURLOPT_RETURNTRANSFER => true,
        CURLOPT_ENCODING => "",
        CURLOPT_MAXREDIRS => 10,
        CURLOPT_TIMEOUT => 0,
        CURLOPT_FOLLOWLOCATION => true,
        CURLOPT_HTTP_VERSION => CURL_HTTP_VERSION_1_1,
        CURLOPT_CUSTOMREQUEST => "POST",
        CURLOPT_POSTFIELDS => array('as_dsc_extensao' => 'XML',
        'as_doc_eletronico'=>'S',
        'as_erro_nota'=>'N',
        'as_msg_nota'=>'teste',
        'ind_doc_eletronico' => 's',
        'ablb_xml'=>base64_encode(file_get_contents($file->getRealPath())) //new \CURLFILE('http://3.22.8.104:8082/storage/'.$destinationPath)
    ),


        CURLOPT_HTTPHEADER => array(
            "client_id: 7ef1d710-35c2-3aa1-82f8-6b82dc1b58d4",
            "access_token:17895c05-6c3f-3d38-9065-bfa1b5294f1a",

        ),
       // CURLOPT_POSTFIELDS => array('dsc_extensao' => '.xml','con_arquivo_doc'=> new \CURLFILE('http://3.22.8.104:8082/storage/energisa%20teste/nota01.xlsx')),
        ));
        //

        $response = curl_exec($curl);

        curl_close($curl);*/
        $curl = curl_init();

        curl_setopt_array($curl, array(
        CURLOPT_URL => "http://hml-api.energisa.io/WSCFSPB_SFC/v1/of_recebe_xml",
        CURLOPT_RETURNTRANSFER => true,
        CURLOPT_ENCODING => "",
        CURLOPT_MAXREDIRS => 10,
        CURLOPT_TIMEOUT => 0,
        CURLOPT_FOLLOWLOCATION => true,
        CURLOPT_HTTP_VERSION => CURL_HTTP_VERSION_1_1,
        CURLOPT_CUSTOMREQUEST => "POST",
        CURLOPT_POSTFIELDS =>"{ \"of_recebe_xml\": {\r\n    \"ablb_xml\":\"PD94bWwgdmVyc2lvbj0iMS4wIj8+CjxuZmVQcm9jIHhtbG5zPSJodHRwOi8vd3d3LnBvcnRhbGZpc2NhbC5pbmYuYnIvbmZlIiB2ZXJzYW89IjQuMDAiPgogIDxORmUgeG1sbnM9Imh0dHA6Ly93d3cucG9ydGFsZmlzY2FsLmluZi5ici9uZmUiPgogICAgPGluZk5GZSB2ZXJzYW89IjQuMDAiIElkPSJORmUzMTIwMDUwNzE4ODI2MjAwMDE3MDU1MDAzMDAwMDEyNjY0MTkyNTAxNTA3OCI+CiAgICAgIDxpZGU+CiAgICAgICAgPGNVRj4zMTwvY1VGPgogICAgICAgIDxjTkY+OTI1MDE1MDc8L2NORj4KICAgICAgICA8bmF0T3A+VmVuZGEgTWVyY2Fkb3JpYXM8L25hdE9wPgogICAgICAgIDxtb2Q+NTU8L21vZD4KICAgICAgICA8c2VyaWU+Mzwvc2VyaWU+CiAgICAgICAgPG5ORj4xMjY2NDwvbk5GPgogICAgICAgIDxkaEVtaT4yMDIwLTA1LTA2VDE0OjI3OjAwLTAzOjAwPC9kaEVtaT4KICAgICAgICA8ZGhTYWlFbnQ+MjAyMC0wNS0wNlQxNDoyNzowMC0wMzowMDwvZGhTYWlFbnQ+CiAgICAgICAgPHRwTkY+MTwvdHBORj4KICAgICAgICA8aWREZXN0PjE8L2lkRGVzdD4KICAgICAgICA8Y011bkZHPjMxMTUzMDA8L2NNdW5GRz4KICAgICAgICA8dHBJbXA+MTwvdHBJbXA+CiAgICAgICAgPHRwRW1pcz4xPC90cEVtaXM+CiAgICAgICAgPGNEVj44PC9jRFY+CiAgICAgICAgPHRwQW1iPjE8L3RwQW1iPgogICAgICAgIDxmaW5ORmU+MTwvZmluTkZlPgogICAgICAgIDxpbmRGaW5hbD4xPC9pbmRGaW5hbD4KICAgICAgICA8aW5kUHJlcz4xPC9pbmRQcmVzPgogICAgICAgIDxwcm9jRW1pPjA8L3Byb2NFbWk+CiAgICAgICAgPHZlclByb2M+Zi0yMDIwPC92ZXJQcm9jPgogICAgICA8L2lkZT4KICAgICAgPGVtaXQ+CiAgICAgICAgPENOUEo+MDcxODgyNjIwMDAxNzA8L0NOUEo+CiAgICAgICAgPHhOb21lPk9GSUNJTkEgRE8gVkFTQ08gREUgQ0FUQUdVQVNFUyBMVERBPC94Tm9tZT4KICAgICAgICA8eEZhbnQ+T0ZJQ0lOQSBETyBWQVNDTzwveEZhbnQ+CiAgICAgICAgPGVuZGVyRW1pdD4KICAgICAgICAgIDx4TGdyPlJ1YSBBTlRFUk8gUklCRUlSTzwveExncj4KICAgICAgICAgIDxucm8+NDYwPC9ucm8+CiAgICAgICAgICA8eEJhaXJybz5QT1BVTEFSPC94QmFpcnJvPgogICAgICAgICAgPGNNdW4+MzExNTMwMDwvY011bj4KICAgICAgICAgIDx4TXVuPkNhdGFndWFzZXM8L3hNdW4+CiAgICAgICAgICA8VUY+TUc8L1VGPgogICAgICAgICAgPENFUD4zNjc3NDU2MDwvQ0VQPgogICAgICAgICAgPGNQYWlzPjEwNTg8L2NQYWlzPgogICAgICAgICAgPHhQYWlzPkJSQVNJTDwveFBhaXM+CiAgICAgICAgICA8Zm9uZT4zMjM0MjE2ODMwPC9mb25lPgogICAgICAgIDwvZW5kZXJFbWl0PgogICAgICAgIDxJRT4xNTMyMDgyMDEwMDk5PC9JRT4KICAgICAgICA8Q1JUPjE8L0NSVD4KICAgICAgPC9lbWl0PgogICAgICA8ZGVzdD4KICAgICAgICA8Q05QSj4wNzExNTg4MDAwMDE5MDwvQ05QSj4KICAgICAgICA8eE5vbWU+RW5lcmdpc2EgU29sdWNvZXMgU0E8L3hOb21lPgogICAgICAgIDxlbmRlckRlc3Q+CiAgICAgICAgICA8eExncj5BdmVuaWRhIE1hbnVlbCBJbmFjaW8gUGVpeG90bzwveExncj4KICAgICAgICAgIDxucm8+Uy9OPC9ucm8+CiAgICAgICAgICA8eEJhaXJybz5QYXJxdWUgSW5kdXN0cmlhbDwveEJhaXJybz4KICAgICAgICAgIDxjTXVuPjMxMTUzMDA8L2NNdW4+CiAgICAgICAgICA8eE11bj5DYXRhZ3Vhc2VzPC94TXVuPgogICAgICAgICAgPFVGPk1HPC9VRj4KICAgICAgICAgIDxDRVA+MzY3NzEwMDA8L0NFUD4KICAgICAgICAgIDxjUGFpcz4xMDU4PC9jUGFpcz4KICAgICAgICAgIDx4UGFpcz5CUkFTSUw8L3hQYWlzPgogICAgICAgIDwvZW5kZXJEZXN0PgogICAgICAgIDxpbmRJRURlc3Q+MTwvaW5kSUVEZXN0PgogICAgICAgIDxJRT4xNTMzNTI2ODQwMDA2PC9JRT4KICAgICAgICA8ZW1haWw+b2ZpY2luYWRvdmFzY28yMDEwQGhvdG1haWwuY29tPC9lbWFpbD4KICAgICAgPC9kZXN0PgogICAgICA8ZGV0IG5JdGVtPSIxIj4KICAgICAgICA8cHJvZD4KICAgICAgICAgIDxjUHJvZD4zNTY2NzwvY1Byb2Q+CiAgICAgICAgICA8Y0VBTj43ODk4NTc3NTcwMzYwPC9jRUFOPgogICAgICAgICAgPHhQcm9kPlJBRElBRE9SIFRST0NBRE9SIERFIENBTE9SIC0gTlQ3MDExNTM0PC94UHJvZD4KICAgICAgICAgIDxOQ00+ODcwODkxMDA8L05DTT4KICAgICAgICAgIDxDRVNUPjAxMDc1MDA8L0NFU1Q+CiAgICAgICAgICA8Q0ZPUD41NDA1PC9DRk9QPgogICAgICAgICAgPHVDb20+UEM8L3VDb20+CiAgICAgICAgICA8cUNvbT4xLjAwMDA8L3FDb20+CiAgICAgICAgICA8dlVuQ29tPjgwNy41MDAwMDAwMDAwPC92VW5Db20+CiAgICAgICAgICA8dlByb2Q+ODA3LjUwPC92UHJvZD4KICAgICAgICAgIDxjRUFOVHJpYj43ODk4NTc3NTcwMzYwPC9jRUFOVHJpYj4KICAgICAgICAgIDx1VHJpYj5QQzwvdVRyaWI+CiAgICAgICAgICA8cVRyaWI+MS4wMDAwPC9xVHJpYj4KICAgICAgICAgIDx2VW5UcmliPjgwNy41MDAwMDAwMDAwPC92VW5UcmliPgogICAgICAgICAgPGluZFRvdD4xPC9pbmRUb3Q+CiAgICAgICAgICA8dkZyZXRlPjczNjQ8L3ZGcmV0ZT4KICAJCSAgPGluZkFEUHJvZD4yMTM8L2luZkFEUHJvZD4KICAgICAgICA8L3Byb2Q+CiAgICAgICAgPGltcG9zdG8+CiAgICAgICAgICA8dlRvdFRyaWI+MjgzLjY3PC92VG90VHJpYj4KICAgICAgICAgIDxJQ01TPgogICAgICAgICAgICA8SUNNU1NONTAwPgogICAgICAgICAgICAgIDxvcmlnPjA8L29yaWc+CiAgICAgICAgICAgICAgPENTT1NOPjUwMDwvQ1NPU04+CiAgICAgICAgICAgICAgPHZCQ1NUUmV0PjAuMDA8L3ZCQ1NUUmV0PgogICAgICAgICAgICAgIDxwU1Q+MTguMDAwMDwvcFNUPgogICAgICAgICAgICAgIDx2SUNNU1N1YnN0aXR1dG8+MC4wMDwvdklDTVNTdWJzdGl0dXRvPgogICAgICAgICAgICAgIDx2SUNNU1NUUmV0PjAuMDA8L3ZJQ01TU1RSZXQ+CiAgICAgICAgICAgIDwvSUNNU1NONTAwPgogICAgICAgICAgPC9JQ01TPgogICAgICAgICAgPElQST4KICAgICAgICAgICAgPGNFbnE+OTk5PC9jRW5xPgogICAgICAgICAgICA8SVBJVHJpYj4KICAgICAgICAgICAgICA8Q1NUPjk5PC9DU1Q+CiAgICAgICAgICAgICAgPHZCQz4wLjAwPC92QkM+CiAgICAgICAgICAgICAgPHBJUEk+MC4wMDAwPC9wSVBJPgogICAgICAgICAgICAgIDx2SVBJPjAuMDA8L3ZJUEk+CiAgICAgICAgICAgIDwvSVBJVHJpYj4KICAgICAgICAgIDwvSVBJPgogICAgICAgICAgPFBJUz4KICAgICAgICAgICAgPFBJU0FsaXE+CiAgICAgICAgICAgICAgPENTVD4wMTwvQ1NUPgogICAgICAgICAgICAgIDx2QkM+MC4wMDwvdkJDPgogICAgICAgICAgICAgIDxwUElTPjAuMDAwMDwvcFBJUz4KICAgICAgICAgICAgICA8dlBJUz4wLjAwPC92UElTPgogICAgICAgICAgICA8L1BJU0FsaXE+CiAgICAgICAgICA8L1BJUz4KICAgICAgICAgIDxDT0ZJTlM+CiAgICAgICAgICAgIDxDT0ZJTlNBbGlxPgogICAgICAgICAgICAgIDxDU1Q+MDE8L0NTVD4KICAgICAgICAgICAgICA8dkJDPjAuMDA8L3ZCQz4KICAgICAgICAgICAgICA8cENPRklOUz4wLjAwMDA8L3BDT0ZJTlM+CiAgICAgICAgICAgICAgPHZDT0ZJTlM+MC4wMDwvdkNPRklOUz4KICAgICAgICAgICAgPC9DT0ZJTlNBbGlxPgogICAgICAgICAgPC9DT0ZJTlM+CiAgICAgICAgPC9pbXBvc3RvPgogICAgICA8L2RldD4KICAgICAgPGRldCBuSXRlbT0iMiI+CiAgICAgICAgPHByb2Q+CiAgICAgICAgICA8Y1Byb2Q+MTkwMzg8L2NQcm9kPgogICAgICAgICAgPGNFQU4+U0VNIEdUSU48L2NFQU4+CiAgICAgICAgICA8eFByb2Q+QURJVElWTyBSQURJQURPUiBBSkFYIFJFRCBQT1dFUiAxTCBPUkdBTjwveFByb2Q+CiAgICAgICAgICA8TkNNPjM4MjAwMDAwPC9OQ00+CiAgICAgICAgICA8Q0VTVD4yODA2MzAwPC9DRVNUPgogICAgICAgICAgPENGT1A+NTQwNTwvQ0ZPUD4KICAgICAgICAgIDx1Q29tPlBDPC91Q29tPgogICAgICAgICAgPHFDb20+My4wMDAwPC9xQ29tPgogICAgICAgICAgPHZVbkNvbT4yNi42MDAwMDAwMDAwPC92VW5Db20+CiAgICAgICAgICA8dlByb2Q+NzkuODA8L3ZQcm9kPgogICAgICAgICAgPGNFQU5UcmliPlNFTSBHVElOPC9jRUFOVHJpYj4KICAgICAgICAgIDx1VHJpYj5QQzwvdVRyaWI+CiAgICAgICAgICA8cVRyaWI+My4wMDAwPC9xVHJpYj4KICAgICAgICAgIDx2VW5UcmliPjI2LjYwMDAwMDAwMDA8L3ZVblRyaWI+CiAgICAgICAgICA8aW5kVG90PjE8L2luZFRvdD4KICAgCQkJPHhQZWQ+I0VORVIxNzMzPC94UGVkPgogICAgICAgIDwvcHJvZD4KICAgICAgICA8aW1wb3N0bz4KICAgICAgICAgIDx2VG90VHJpYj44Ljk1PC92VG90VHJpYj4KICAgICAgICAgIDxJQ01TPgogICAgICAgICAgICA8SUNNU1NONTAwPgogICAgICAgICAgICAgIDxvcmlnPjA8L29yaWc+CiAgICAgICAgICAgICAgPENTT1NOPjUwMDwvQ1NPU04+CiAgICAgICAgICAgICAgPHZCQ1NUUmV0PjAuMDA8L3ZCQ1NUUmV0PgogICAgICAgICAgICAgIDxwU1Q+MTguMDAwMDwvcFNUPgogICAgICAgICAgICAgIDx2SUNNU1N1YnN0aXR1dG8+MC4wMDwvdklDTVNTdWJzdGl0dXRvPgogICAgICAgICAgICAgIDx2SUNNU1NUUmV0PjAuMDA8L3ZJQ01TU1RSZXQ+CiAgICAgICAgICAgIDwvSUNNU1NONTAwPgogICAgICAgICAgPC9JQ01TPgogICAgICAgICAgPElQST4KICAgICAgICAgICAgPGNFbnE+OTk5PC9jRW5xPgogICAgICAgICAgICA8SVBJVHJpYj4KICAgICAgICAgICAgICA8Q1NUPjk5PC9DU1Q+CiAgICAgICAgICAgICAgPHZCQz4wLjAwPC92QkM+CiAgICAgICAgICAgICAgPHBJUEk+MC4wMDAwPC9wSVBJPgogICAgICAgICAgICAgIDx2SVBJPjAuMDA8L3ZJUEk+CiAgICAgICAgICAgIDwvSVBJVHJpYj4KICAgICAgICAgIDwvSVBJPgogICAgICAgICAgPFBJUz4KICAgICAgICAgICAgPFBJU091dHI+CiAgICAgICAgICAgICAgPENTVD45OTwvQ1NUPgogICAgICAgICAgICAgIDx2QkM+MC4wMDwvdkJDPgogICAgICAgICAgICAgIDxwUElTPjAuMDAwMDwvcFBJUz4KICAgICAgICAgICAgICA8dlBJUz4wLjAwPC92UElTPgogICAgICAgICAgICA8L1BJU091dHI+CiAgICAgICAgICA8L1BJUz4KICAgICAgICAgIDxDT0ZJTlM+CiAgICAgICAgICAgIDxDT0ZJTlNPdXRyPgogICAgICAgICAgICAgIDxDU1Q+OTk8L0NTVD4KICAgICAgICAgICAgICA8dkJDPjAuMDA8L3ZCQz4KICAgICAgICAgICAgICA8cENPRklOUz4wLjAwMDA8L3BDT0ZJTlM+CiAgICAgICAgICAgICAgPHZDT0ZJTlM+MC4wMDwvdkNPRklOUz4KICAgICAgICAgICAgPC9DT0ZJTlNPdXRyPgogICAgICAgICAgPC9DT0ZJTlM+CiAgICAgICAgPC9pbXBvc3RvPgogICAgICA8L2RldD4KICAgICAgPGRldCBuSXRlbT0iMyI+CiAgICAgICAgPHByb2Q+CiAgICAgICAgICA8Y1Byb2Q+MjM3MDM8L2NQcm9kPgogICAgICAgICAgPGNFQU4+Nzg5MzM3MTM5OTU4MjwvY0VBTj4KICAgICAgICAgIDx4UHJvZD5TSUxJQ09ORSBBQ0VUSUNPIENJTlpBIDA5ODEwMTY1MDwveFByb2Q+CiAgICAgICAgICA8TkNNPjMyMTQxMDEwPC9OQ00+CiAgICAgICAgICA8Q0VTVD4wMTk5OTAwPC9DRVNUPgogICAgICAgICAgPENGT1A+NTQwNTwvQ0ZPUD4KICAgICAgICAgIDx1Q29tPlBDPC91Q29tPgogICAgICAgICAgPHFDb20+MS4wMDAwPC9xQ29tPgogICAgICAgICAgPHZVbkNvbT4xOS4wMDAwMDAwMDAwPC92VW5Db20+CiAgICAgICAgICA8dlByb2Q+MTkuMDA8L3ZQcm9kPgogICAgICAgICAgPGNFQU5UcmliPjc4OTMzNzEzOTk1ODI8L2NFQU5UcmliPgogICAgICAgICAgPHVUcmliPlBDPC91VHJpYj4KICAgICAgICAgIDxxVHJpYj4xLjAwMDA8L3FUcmliPgogICAgICAgICAgPHZVblRyaWI+MTkuMDAwMDAwMDAwMDwvdlVuVHJpYj4KICAgICAgICAgIDxpbmRUb3Q+MTwvaW5kVG90PgogICAgICAgIDwvcHJvZD4KICAgICAgICA8aW1wb3N0bz4KICAgICAgICAgIDx2VG90VHJpYj40LjUwPC92VG90VHJpYj4KICAgICAgICAgIDxJQ01TPgogICAgICAgICAgICA8SUNNU1NONTAwPgogICAgICAgICAgICAgIDxvcmlnPjA8L29yaWc+CiAgICAgICAgICAgICAgPENTT1NOPjUwMDwvQ1NPU04+CiAgICAgICAgICAgICAgPHZCQ1NUUmV0PjAuMDA8L3ZCQ1NUUmV0PgogICAgICAgICAgICAgIDxwU1Q+MTguMDAwMDwvcFNUPgogICAgICAgICAgICAgIDx2SUNNU1N1YnN0aXR1dG8+MC4wMDwvdklDTVNTdWJzdGl0dXRvPgogICAgICAgICAgICAgIDx2SUNNU1NUUmV0PjAuMDA8L3ZJQ01TU1RSZXQ+CiAgICAgICAgICAgIDwvSUNNU1NONTAwPgogICAgICAgICAgPC9JQ01TPgogICAgICAgICAgPElQST4KICAgICAgICAgICAgPGNFbnE+OTk5PC9jRW5xPgogICAgICAgICAgICA8SVBJVHJpYj4KICAgICAgICAgICAgICA8Q1NUPjk5PC9DU1Q+CiAgICAgICAgICAgICAgPHZCQz4wLjAwPC92QkM+CiAgICAgICAgICAgICAgPHBJUEk+MC4wMDAwPC9wSVBJPgogICAgICAgICAgICAgIDx2SVBJPjAuMDA8L3ZJUEk+CiAgICAgICAgICAgIDwvSVBJVHJpYj4KICAgICAgICAgIDwvSVBJPgogICAgICAgICAgPFBJUz4KICAgICAgICAgICAgPFBJU091dHI+CiAgICAgICAgICAgICAgPENTVD45OTwvQ1NUPgogICAgICAgICAgICAgIDx2QkM+MC4wMDwvdkJDPgogICAgICAgICAgICAgIDxwUElTPjAuMDAwMDwvcFBJUz4KICAgICAgICAgICAgICA8dlBJUz4wLjAwPC92UElTPgogICAgICAgICAgICA8L1BJU091dHI+CiAgICAgICAgICA8L1BJUz4KICAgICAgICAgIDxDT0ZJTlM+CiAgICAgICAgICAgIDxDT0ZJTlNPdXRyPgogICAgICAgICAgICAgIDxDU1Q+OTk8L0NTVD4KICAgICAgICAgICAgICA8dkJDPjAuMDA8L3ZCQz4KICAgICAgICAgICAgICA8cENPRklOUz4wLjAwMDA8L3BDT0ZJTlM+CiAgICAgICAgICAgICAgPHZDT0ZJTlM+MC4wMDwvdkNPRklOUz4KICAgICAgICAgICAgPC9DT0ZJTlNPdXRyPgogICAgICAgICAgPC9DT0ZJTlM+CiAgICAgICAgPC9pbXBvc3RvPgogICAgICA8L2RldD4KICAgICAgPGRldCBuSXRlbT0iNCI+CiAgICAgICAgPHByb2Q+CiAgICAgICAgICA8Y1Byb2Q+MzIxNzk8L2NQcm9kPgogICAgICAgICAgPGNFQU4+U0VNIEdUSU48L2NFQU4+CiAgICAgICAgICA8eFByb2Q+QUJSQUNBREVJUkEgMjJYMzIgNDAyMjAzMjwveFByb2Q+CiAgICAgICAgICA8TkNNPjczMjYxOTAwPC9OQ00+CiAgICAgICAgICA8Q0VTVD4xMDA2MjAwPC9DRVNUPgogICAgICAgICAgPENGT1A+NTQwNTwvQ0ZPUD4KICAgICAgICAgIDx1Q29tPlBDPC91Q29tPgogICAgICAgICAgPHFDb20+NC4wMDAwPC9xQ29tPgogICAgICAgICAgPHZVbkNvbT40LjAwMDAwMDAwMDA8L3ZVbkNvbT4KICAgICAgICAgIDx2UHJvZD4xNi4wMDwvdlByb2Q+CiAgICAgICAgICA8Y0VBTlRyaWI+U0VNIEdUSU48L2NFQU5UcmliPgogICAgICAgICAgPHVUcmliPlBDPC91VHJpYj4KICAgICAgICAgIDxxVHJpYj40LjAwMDA8L3FUcmliPgogICAgICAgICAgPHZVblRyaWI+NC4wMDAwMDAwMDAwPC92VW5UcmliPgogICAgICAgICAgPGluZFRvdD4xPC9pbmRUb3Q+CiAgICAgICAgPC9wcm9kPgogICAgICAgIDxpbXBvc3RvPgogICAgICAgICAgPHZUb3RUcmliPjQuNjg8L3ZUb3RUcmliPgogICAgICAgICAgPElDTVM+CiAgICAgICAgICAgIDxJQ01TU041MDA+CiAgICAgICAgICAgICAgPG9yaWc+MDwvb3JpZz4KICAgICAgICAgICAgICA8Q1NPU04+NTAwPC9DU09TTj4KICAgICAgICAgICAgICA8dkJDU1RSZXQ+MC4wMDwvdkJDU1RSZXQ+CiAgICAgICAgICAgICAgPHBTVD4xOC4wMDAwPC9wU1Q+CiAgICAgICAgICAgICAgPHZJQ01TU3Vic3RpdHV0bz4wLjAwPC92SUNNU1N1YnN0aXR1dG8+CiAgICAgICAgICAgICAgPHZJQ01TU1RSZXQ+MC4wMDwvdklDTVNTVFJldD4KICAgICAgICAgICAgPC9JQ01TU041MDA+CiAgICAgICAgICA8L0lDTVM+CiAgICAgICAgICA8SVBJPgogICAgICAgICAgICA8Y0VucT45OTk8L2NFbnE+CiAgICAgICAgICAgIDxJUElUcmliPgogICAgICAgICAgICAgIDxDU1Q+OTk8L0NTVD4KICAgICAgICAgICAgICA8dkJDPjAuMDA8L3ZCQz4KICAgICAgICAgICAgICA8cElQST4wLjAwMDA8L3BJUEk+CiAgICAgICAgICAgICAgPHZJUEk+MC4wMDwvdklQST4KICAgICAgICAgICAgPC9JUElUcmliPgogICAgICAgICAgPC9JUEk+CiAgICAgICAgICA8UElTPgogICAgICAgICAgICA8UElTT3V0cj4KICAgICAgICAgICAgICA8Q1NUPjk5PC9DU1Q+CiAgICAgICAgICAgICAgPHZCQz4wLjAwPC92QkM+CiAgICAgICAgICAgICAgPHBQSVM+MC4wMDAwPC9wUElTPgogICAgICAgICAgICAgIDx2UElTPjAuMDA8L3ZQSVM+CiAgICAgICAgICAgIDwvUElTT3V0cj4KICAgICAgICAgIDwvUElTPgogICAgICAgICAgPENPRklOUz4KICAgICAgICAgICAgPENPRklOU091dHI+CiAgICAgICAgICAgICAgPENTVD45OTwvQ1NUPgogICAgICAgICAgICAgIDx2QkM+MC4wMDwvdkJDPgogICAgICAgICAgICAgIDxwQ09GSU5TPjAuMDAwMDwvcENPRklOUz4KICAgICAgICAgICAgICA8dkNPRklOUz4wLjAwPC92Q09GSU5TPgogICAgICAgICAgICA8L0NPRklOU091dHI+CiAgICAgICAgICA8L0NPRklOUz4KICAgICAgICA8L2ltcG9zdG8+CiAgICAgIDwvZGV0PgogICAgICA8ZGV0IG5JdGVtPSI1Ij4KICAgICAgICA8cHJvZD4KICAgICAgICAgIDxjUHJvZD4xNTE3OTwvY1Byb2Q+CiAgICAgICAgICA8Y0VBTj5TRU0gR1RJTjwvY0VBTj4KICAgICAgICAgIDx4UHJvZD5BQlJBQ0FERUlSQSBNSUNSTyA5TU0gOVgxMyAwMDAzMDA5MDEzPC94UHJvZD4KICAgICAgICAgIDxOQ00+NzMyNjE5MDA8L05DTT4KICAgICAgICAgIDxDRVNUPjEwMDYyMDA8L0NFU1Q+CiAgICAgICAgICA8Q0ZPUD41NDA1PC9DRk9QPgogICAgICAgICAgPHVDb20+VU48L3VDb20+CiAgICAgICAgICA8cUNvbT42LjAwMDA8L3FDb20+CiAgICAgICAgICA8dlVuQ29tPjIuMDAwMDAwMDAwMDwvdlVuQ29tPgogICAgICAgICAgPHZQcm9kPjEyLjAwPC92UHJvZD4KICAgICAgICAgIDxjRUFOVHJpYj5TRU0gR1RJTjwvY0VBTlRyaWI+CiAgICAgICAgICA8dVRyaWI+VU48L3VUcmliPgogICAgICAgICAgPHFUcmliPjYuMDAwMDwvcVRyaWI+CiAgICAgICAgICA8dlVuVHJpYj4yLjAwMDAwMDAwMDA8L3ZVblRyaWI+CiAgICAgICAgICA8aW5kVG90PjE8L2luZFRvdD4KICAgICAgICA8L3Byb2Q+CiAgICAgICAgPGltcG9zdG8+CiAgICAgICAgICA8dlRvdFRyaWI+My41MTwvdlRvdFRyaWI+CiAgICAgICAgICA8SUNNUz4KICAgICAgICAgICAgPElDTVNTTjUwMD4KICAgICAgICAgICAgICA8b3JpZz4wPC9vcmlnPgogICAgICAgICAgICAgIDxDU09TTj41MDA8L0NTT1NOPgogICAgICAgICAgICAgIDx2QkNTVFJldD4wLjAwPC92QkNTVFJldD4KICAgICAgICAgICAgICA8cFNUPjE4LjAwMDA8L3BTVD4KICAgICAgICAgICAgICA8dklDTVNTdWJzdGl0dXRvPjAuMDA8L3ZJQ01TU3Vic3RpdHV0bz4KICAgICAgICAgICAgICA8dklDTVNTVFJldD4wLjAwPC92SUNNU1NUUmV0PgogICAgICAgICAgICA8L0lDTVNTTjUwMD4KICAgICAgICAgIDwvSUNNUz4KICAgICAgICAgIDxJUEk+CiAgICAgICAgICAgIDxjRW5xPjk5OTwvY0VucT4KICAgICAgICAgICAgPElQSVRyaWI+CiAgICAgICAgICAgICAgPENTVD45OTwvQ1NUPgogICAgICAgICAgICAgIDx2QkM+MC4wMDwvdkJDPgogICAgICAgICAgICAgIDxwSVBJPjAuMDAwMDwvcElQST4KICAgICAgICAgICAgICA8dklQST4wLjAwPC92SVBJPgogICAgICAgICAgICA8L0lQSVRyaWI+CiAgICAgICAgICA8L0lQST4KICAgICAgICAgIDxQSVM+CiAgICAgICAgICAgIDxQSVNBbGlxPgogICAgICAgICAgICAgIDxDU1Q+MDE8L0NTVD4KICAgICAgICAgICAgICA8dkJDPjAuMDA8L3ZCQz4KICAgICAgICAgICAgICA8cFBJUz4wLjAwMDA8L3BQSVM+CiAgICAgICAgICAgICAgPHZQSVM+MC4wMDwvdlBJUz4KICAgICAgICAgICAgPC9QSVNBbGlxPgogICAgICAgICAgPC9QSVM+CiAgICAgICAgICA8Q09GSU5TPgogICAgICAgICAgICA8Q09GSU5TT3V0cj4KICAgICAgICAgICAgICA8Q1NUPjk5PC9DU1Q+CiAgICAgICAgICAgICAgPHZCQz4wLjAwPC92QkM+CiAgICAgICAgICAgICAgPHBDT0ZJTlM+MC4wMDAwPC9wQ09GSU5TPgogICAgICAgICAgICAgIDx2Q09GSU5TPjAuMDA8L3ZDT0ZJTlM+CiAgICAgICAgICAgIDwvQ09GSU5TT3V0cj4KICAgICAgICAgIDwvQ09GSU5TPgogICAgICAgIDwvaW1wb3N0bz4KICAgICAgPC9kZXQ+CiAgICAgIDx0b3RhbD4KICAgICAgICA8SUNNU1RvdD4KICAgICAgICAgIDx2QkM+MC4wMDwvdkJDPgogICAgICAgICAgPHZJQ01TPjAuMDA8L3ZJQ01TPgogICAgICAgICAgPHZJQ01TRGVzb24+MC4wMDwvdklDTVNEZXNvbj4KICAgICAgICAgIDx2RkNQPjAuMDA8L3ZGQ1A+CiAgICAgICAgICA8dkJDU1Q+MC4wMDwvdkJDU1Q+CiAgICAgICAgICA8dlNUPjAuMDA8L3ZTVD4KICAgICAgICAgIDx2RkNQU1Q+MC4wMDwvdkZDUFNUPgogICAgICAgICAgPHZGQ1BTVFJldD4wLjAwPC92RkNQU1RSZXQ+CiAgICAgICAgICA8dlByb2Q+OTM0LjMwPC92UHJvZD4KICAgICAgICAgIDx2RnJldGU+MC4wMDwvdkZyZXRlPgogICAgICAgICAgPHZTZWc+MC4wMDwvdlNlZz4KICAgICAgICAgIDx2RGVzYz4wLjAwPC92RGVzYz4KICAgICAgICAgIDx2SUk+MC4wMDwvdklJPgogICAgICAgICAgPHZJUEk+MC4wMDwvdklQST4KICAgICAgICAgIDx2SVBJRGV2b2w+MC4wMDwvdklQSURldm9sPgogICAgICAgICAgPHZQSVM+MC4wMDwvdlBJUz4KICAgICAgICAgIDx2Q09GSU5TPjAuMDA8L3ZDT0ZJTlM+CiAgICAgICAgICA8dk91dHJvPjAuMDA8L3ZPdXRybz4KICAgICAgICAgIDx2TkY+OTM0LjMwPC92TkY+CiAgICAgICAgICA8dlRvdFRyaWI+MzA1LjMxPC92VG90VHJpYj4KICAgICAgICA8L0lDTVNUb3Q+CiAgICAgIDwvdG90YWw+CiAgICAgIDx0cmFuc3A+CiAgICAgICAgPG1vZEZyZXRlPjk8L21vZEZyZXRlPgogICAgICA8L3RyYW5zcD4KICAgICAgPHBhZz4KICAgICAgICA8ZGV0UGFnPgogICAgICAgICAgPHRQYWc+OTA8L3RQYWc+CiAgICAgICAgICA8dlBhZz4wLjAwPC92UGFnPgogICAgICAgIDwvZGV0UGFnPgogICAgICA8L3BhZz4KICAgICAgPGluZkFkaWM+CiAgICAgICAgPGluZkNwbD5JLURPQy5FTUlUSURPIFAvTUUgT1UgRVBQIE9QVEFOVEUgUC9TSU1QTEVTIE5BQ0lPTkFMIDs7SUktTkFPIEdFUkEgRElSRUlUTyBBIENSRURJVE8gRklTQ0FMIERFIElQSSA7O1ZFSUNVTE86IEFNQVJPSzs7UExBQ0E6IEhMTy03NDg1OztGUk9UQTogMzEyOTs7S006IDI4MS4xMDN8TUQ1OiBEMzk3ODlCN0IzQ0EzMEI5Q0ZCQUU3M0EyMzQ1QzlDMXxUcmliIEFwcm94LiBSJCAxNTEsNTAgRmVkIC0gUiQgMTUzLDgxIEVzdCAtIFIkIDAsMDAgTXVuIC8gRm9udGU6SUJQVC9lbXByZXNvbWUgNkEwOThFfDwvaW5mQ3BsPgogICAgICA8L2luZkFkaWM+CiAgICA8L2luZk5GZT4KICAgIDxTaWduYXR1cmUgeG1sbnM9Imh0dHA6Ly93d3cudzMub3JnLzIwMDAvMDkveG1sZHNpZyMiPgogICAgICA8U2lnbmVkSW5mbz4KICAgICAgICA8Q2Fub25pY2FsaXphdGlvbk1ldGhvZCBBbGdvcml0aG09Imh0dHA6Ly93d3cudzMub3JnL1RSLzIwMDEvUkVDLXhtbC1jMTRuLTIwMDEwMzE1Ii8+CiAgICAgICAgPFNpZ25hdHVyZU1ldGhvZCBBbGdvcml0aG09Imh0dHA6Ly93d3cudzMub3JnLzIwMDAvMDkveG1sZHNpZyNyc2Etc2hhMSIvPgogICAgICAgIDxSZWZlcmVuY2UgVVJJPSIjTkZlMzEyMDA1MDcxODgyNjIwMDAxNzA1NTAwMzAwMDAxMjY2NDE5MjUwMTUwNzgiPgogICAgICAgICAgPFRyYW5zZm9ybXM+CiAgICAgICAgICAgIDxUcmFuc2Zvcm0gQWxnb3JpdGhtPSJodHRwOi8vd3d3LnczLm9yZy8yMDAwLzA5L3htbGRzaWcjZW52ZWxvcGVkLXNpZ25hdHVyZSIvPgogICAgICAgICAgICA8VHJhbnNmb3JtIEFsZ29yaXRobT0iaHR0cDovL3d3dy53My5vcmcvVFIvMjAwMS9SRUMteG1sLWMxNG4tMjAwMTAzMTUiLz4KICAgICAgICAgIDwvVHJhbnNmb3Jtcz4KICAgICAgICAgIDxEaWdlc3RNZXRob2QgQWxnb3JpdGhtPSJodHRwOi8vd3d3LnczLm9yZy8yMDAwLzA5L3htbGRzaWcjc2hhMSIvPgogICAgICAgICAgPERpZ2VzdFZhbHVlPlBDOEpDN20wY3BCbkFPR2NKUzZ5dWt5YVB6Yz08L0RpZ2VzdFZhbHVlPgogICAgICAgIDwvUmVmZXJlbmNlPgogICAgICA8L1NpZ25lZEluZm8+CiAgICAgIDxTaWduYXR1cmVWYWx1ZT5TZ2hxK2orT2pFNG1LSlU1V1c1MjNSV3hQTUJ2aXBEK2tJMXlvRC8veDllWmNXM2ZRWWNXZlVMUS81N2t4NXRkeE5aTktxTXZ6RXRxVXhGRG9mMTV3aEdTYmZta0xjdWdJMGxmWHk1cEhZaFNCcXVocVQ4N1g3K3hNWXgxc1pFdkxDVmQ3Zi9jUmNGdU1LbTdHdUZLME1vaWxNdkx0REc3RFNWbi9XY2pRa3RsT2crdlduUXNtR2lyejZ1MlJSalgvN01FUVJGSGVNTGVTSUZoVTluRkVMRzY5ME40SEVqLzlpeWNYZ2lzeTlRWUVzV1hSNzh0dEx0a3pSQVY0cTNsL3NITTVYUHc1WlUxWHMrdTB0TU9Wc3BFODRhUEJNcDdXeTFodTh0bDh6Z3h5MEFPcmZJY09iMFlKMzRSSDJvRUdHekFNeXVpSGU4THE4QlVCRGtabFE9PTwvU2lnbmF0dXJlVmFsdWU+CiAgICAgIDxLZXlJbmZvPgogICAgICAgIDxYNTA5RGF0YT4KICAgICAgICAgIDxYNTA5Q2VydGlmaWNhdGU+TUlJSUxEQ0NCaFNnQXdJQkFnSUlLZHBQMzdBZkg5TXdEUVlKS29aSWh2Y05BUUVMQlFBd2RURUxNQWtHQTFVRUJoTUNRbEl4RXpBUkJnTlZCQW9NQ2tsRFVDMUNjbUZ6YVd3eE5qQTBCZ05WQkFzTUxWTmxZM0psZEdGeWFXRWdaR0VnVW1WalpXbDBZU0JHWldSbGNtRnNJR1J2SUVKeVlYTnBiQ0F0SUZKR1FqRVpNQmNHQTFVRUF3d1FRVU1nVTBWU1FWTkJJRkpHUWlCMk5UQWVGdzB4T1RFeU1EVXhPRE14TURCYUZ3MHlNREV5TURReE9ETXhNREJhTUlJQk1qRUxNQWtHQTFVRUJoTUNRbEl4Q3pBSkJnTlZCQWdNQWsxSE1STXdFUVlEVlFRSERBcERRVlJCUjFWQlUwVlRNUk13RVFZRFZRUUtEQXBKUTFBdFFuSmhjMmxzTVJnd0ZnWURWUVFMREE4d01EQXdNREV3TURrek9UUXpOekF4TmpBMEJnTlZCQXNNTFZObFkzSmxkR0Z5YVdFZ1pHRWdVbVZqWldsMFlTQkdaV1JsY21Gc0lHUnZJRUp5WVhOcGJDQXRJRkpHUWpFV01CUUdBMVVFQ3d3TlVrWkNJR1V0UTA1UVNpQkJNVEVaTUJjR0ExVUVDd3dRUVVNZ1UwVlNRVk5CSUZKR1FpQjJOVEVYTUJVR0ExVUVDd3dPTVRBNE56RXdPVEV3TURBeE9UUXhFVEFQQmdOVkJBc01DRUZTSUVORlRrbE9NVHN3T1FZRFZRUUREREpQUmtsRFNVNUJJRVJQSUZaQlUwTlBJRVJGSUVOQlZFRkhWVUZUUlZNZ1RGUkVRVG93TnpFNE9ESTJNakF3TURFM01EQ0NBU0l3RFFZSktvWklodmNOQVFFQkJRQURnZ0VQQURDQ0FRb0NnZ0VCQU5pNjlURXIyODJnT0xaOGxyN2swL1BhTkk5VEFxRUFjR05PSFhoQjF5QVdlanpQVDVzV1Y4cERTdkpYU2pJbTkxbGhsS2R6d0t6UDZ3SDNGZkVtV2RmWWJ3VURQdERYNjVBeTZmWDY2ZjZrSE1YWUJOZERLbkRWRU9nMXJhZHZwLzJubTVoYTJBNHhLVzltM3RYUTNqc1U3OHhmVEUweWNDN1ArME04Y2tMT0xEVUxKbHlIZ1g4NzlUcElMZjRmU1JsUVhtSEdJbDdyZm9VbTZTZG9RbVE1NnJydW9HRmM5YWZkbDZDTG4rOGxkeWVGV2huV0xNNmpRd3hjWEFhN1g5MmV6OEJrcUhrbXFQZy9ESE1KOEVjcDN2SWw4YUdwKzMxVUUyakx4dkQ4V3Z2elFnc3kzbUlrMXVOSElUWTlMNEtWVU1tYkpOakYzRGJUeVJqbjBxY0NBd0VBQWFPQ0F2OHdnZ0w3TUFrR0ExVWRFd1FDTUFBd0h3WURWUjBqQkJnd0ZvQVU3UEZCVVZlbzVqcnBYck9nSXZrSWlyVTZoNDh3Z1prR0NDc0dBUVVGQndFQkJJR01NSUdKTUVnR0NDc0dBUVVGQnpBQ2hqeG9kSFJ3T2k4dmQzZDNMbU5sY25ScFptbGpZV1J2WkdsbmFYUmhiQzVqYjIwdVluSXZZMkZrWldsaGN5OXpaWEpoYzJGeVptSjJOUzV3TjJJd1BRWUlLd1lCQlFVSE1BR0dNV2gwZEhBNkx5OXZZM053TG1ObGNuUnBabWxqWVdSdlpHbG5hWFJoYkM1amIyMHVZbkl2YzJWeVlYTmhjbVppZGpVd2djOEdBMVVkRVFTQnh6Q0J4SUVsUTA5T1ZFRlVUeTVEUlZKVVNVWkpRMEZFVDBOUFRsUkJRa2xNUUVkTlFVbE1Ma05QVGFBb0JnVmdUQUVEQXFBZkV4MUJUbFJQVGtsUElGWkJVME5QSUZCSlRVVk9WRVZNSUVwVlRrbFBVcUFaQmdWZ1RBRURBNkFRRXc0d056RTRPREkyTWpBd01ERTNNS0E5QmdWZ1RBRURCS0EwRXpJd016RXdNVGs0TURBek9UQTFNalE1TmpReU1EQXdNREF3TURBd01EQXdNREF3TUUxSE1UQTVPRGt3TkRsVFUxQk5SNkFYQmdWZ1RBRURCNkFPRXd3d01EQXdNREF3TURBd01EQXdjUVlEVlIwZ0JHb3dhREJtQmdaZ1RBRUNBUTB3WERCYUJnZ3JCZ0VGQlFjQ0FSWk9hSFIwY0RvdkwzQjFZbXhwWTJGallXOHVZMlZ5ZEdsbWFXTmhaRzlrYVdkcGRHRnNMbU52YlM1aWNpOXlaWEJ2YzJsMGIzSnBieTlrY0dNdlpHVmpiR0Z5WVdOaGJ5MXlabUl1Y0dSbU1CMEdBMVVkSlFRV01CUUdDQ3NHQVFVRkJ3TUNCZ2dyQmdFRkJRY0RCRENCblFZRFZSMGZCSUdWTUlHU01FcWdTS0JHaGtSb2RIUndPaTh2ZDNkM0xtTmxjblJwWm1sallXUnZaR2xuYVhSaGJDNWpiMjB1WW5JdmNtVndiM05wZEc5eWFXOHZiR055TDNObGNtRnpZWEptWW5ZMUxtTnliREJFb0VLZ1FJWSthSFIwY0RvdkwyeGpjaTVqWlhKMGFXWnBZMkZrYjNNdVkyOXRMbUp5TDNKbGNHOXphWFJ2Y21sdkwyeGpjaTl6WlhKaGMyRnlabUoyTlM1amNtd3dIUVlEVlIwT0JCWUVGRFhuQ3JCUU5lRjNSNDNsTS9pVjJuTUJ2ZmxzTUE0R0ExVWREd0VCL3dRRUF3SUY0REFOQmdrcWhraUc5dzBCQVFzRkFBT0NBZ0VBcmpCWmxQemtPcXJDdFNIckcvL0hKMSt5N3VUZjJOU2ZGZGw0b3VmREJKR0dZOHJhMlMwV3VDbGd3dGl5MjlZOFU3YTg0WkpiTXIyVlB1SklkNjE0QURxTjZWbEJodFdNby9qOGNwUjFUZWNCaEFVdlpZWW9OR1FJVENhbHBXc2FNd0xXRlVPQytFS1JxaWVvbTVueS9OUFhvSWtyRzhmZEZJalJMOU01UUhLSXJqZEZLMG8zZmlIYWJibE5FVVpMNFBCMzZmdXlDOXpzRkVkVytiQmttNSt0UzNEdnpFT3F2UFF6ZW5Yam5tVU5CTzRhNXEwY3lTWk5yUW51YjFKdFhhZnIyRUhIZUN6a0JtSmJScjIrOG05R29YdE92UFhjZ0JwQW5INmkrL25FVDJrTTgvZlA5MSs0UG9wNDZqQnRGdmN3dUJvZTFXYW15K0NDT01SU0x6dWxieEdsYXdZWjF2Ti9EL0g0YTVKTEVRYlg2V2MwdWo0MjV1ZHllY0RKYkJ1VjhQa0VYNjY4aGlUNXhPTE52d2hkRU95Rk12TTRyMlJKSjhjeEZNdUFWM2tzcE5pcVBkU2xkTHUxVm4xMldrNWFFVG5TMi9zQXBtcG1xZXIrQW9rQVFOblEyeFdSOU52Uk5iaGc5VHhqVU1XM24wQnozWmVVZzN2V1FWSm5nRm8xYkZtVUlTWXhzWHRaUzFMakc2NEtsYzhxdnc4eWhWcFc5bHRtSk9mWUx4RHF0bGZHVmRzSGdUV0oyZG9iZmkvRlFhNVIxSHJLdTBLcUdYbHg1WDZyYUV6SzRpY3JhM2NSeS9MUEVNd2VLWm40dTNOTGluYUJOMDFCeDBOQk11NmxiUXdKWXdtNEZHSGtPWGpBR3VYQVJTUHlqbGU5aVl1U1ZoYkRhaUU9PC9YNTA5Q2VydGlmaWNhdGU+CiAgICAgICAgPC9YNTA5RGF0YT4KICAgICAgPC9LZXlJbmZvPgogICAgPC9TaWduYXR1cmU+CiAgPC9ORmU+CiAgPHByb3RORmUgdmVyc2FvPSI0LjAwIj4KICAgIDxpbmZQcm90IElkPSJJRDEzMTIwMzY2NDcyOTg2OSI+CiAgICAgIDx0cEFtYj4xPC90cEFtYj4KICAgICAgPHZlckFwbGljPjE0LjQuMTItTUExPC92ZXJBcGxpYz4KICAgICAgPGNoTkZlPjMxMjAwNTA3MTg4MjYyMDAwMTcwNTUwMDMwMDAwMTI2NjQxOTI1MDE1MDc4PC9jaE5GZT4KICAgICAgPGRoUmVjYnRvPjIwMjAtMDUtMDZUMTQ6NDk6MzAtMDM6MDA8L2RoUmVjYnRvPgogICAgICA8blByb3Q+MTMxMjAzNjY0NzI5ODY5PC9uUHJvdD4KICAgICAgPGRpZ1ZhbD5QQzhKQzdtMGNwQm5BT0djSlM2eXVreWFQemM9PC9kaWdWYWw+CiAgICAgIDxjU3RhdD4xMDA8L2NTdGF0PgogICAgICA8eE1vdGl2bz5BdXRvcml6YWRvIG8gdXNvIGRhIE5GLWU8L3hNb3Rpdm8+CiAgICA8L2luZlByb3Q+CiAgPC9wcm90TkZlPgo8L25mZVByb2M+Cg==\",\r\n    \"as_dsc_extensao\":\"XML\",\r\n    \"as_doc_eletronico\":\"S\",\r\n    \"as_erro_nota\":\"N\",\r\n    \"as_msg_nota\": \"\"\r\n}\r\n}",
        CURLOPT_HTTPHEADER => array(
            "client_id: 7ef1d710-35c2-3aa1-82f8-6b82dc1b58d4",
            "access_token: 18746fb7-a171-3bd1-898e-8f829c9e5ce7",
            "Content-Type: application/json"
        ),
        ));

        $response = curl_exec($curl);

        curl_close($curl);
        dd($response);
        Flash::success('Nota Enviada com Sucesso!');


        return redirect(route('envioNotaServicos.index'));
    }

    /**
     * Display the specified EnvioNotaServico.
     *
     * @param int $id
     *
     * @return Response
     */
    public function show($id)
    {
        $envioNotaServico = $this->envioNotaServicoRepository->find($id);

        if (empty($envioNotaServico)) {
            Flash::error('Envio Nota Servico not found');

            return redirect(route('envioNotaServicos.index'));
        }

        return view('envio_nota_servicos.show')->with('envioNotaServico', $envioNotaServico);
    }

    /**
     * Show the form for editing the specified EnvioNotaServico.
     *
     * @param int $id
     *
     * @return Response
     */
    public function edit($id)
    {
        $envioNotaServico = $this->envioNotaServicoRepository->find($id);

        if (empty($envioNotaServico)) {
            Flash::error('Envio Nota Servico not found');

            return redirect(route('envioNotaServicos.index'));
        }

        return view('envio_nota_servicos.edit')->with('envioNotaServico', $envioNotaServico);
    }

    /**
     * Update the specified EnvioNotaServico in storage.
     *
     * @param int $id
     * @param UpdateEnvioNotaServicoRequest $request
     *
     * @return Response
     */
    public function update($id, UpdateEnvioNotaServicoRequest $request)
    {
        $envioNotaServico = $this->envioNotaServicoRepository->find($id);

        if (empty($envioNotaServico)) {
            Flash::error('Envio Nota Servico not found');

            return redirect(route('envioNotaServicos.index'));
        }

        $envioNotaServico = $this->envioNotaServicoRepository->update($request->all(), $id);

        Flash::success('Envio Nota Servico updated successfully.');

        return redirect(route('envioNotaServicos.index'));
    }

    /**
     * Remove the specified EnvioNotaServico from storage.
     *
     * @param int $id
     *
     * @throws \Exception
     *
     * @return Response
     */
    public function destroy($id)
    {
        $envioNotaServico = $this->envioNotaServicoRepository->find($id);

        if (empty($envioNotaServico)) {
            Flash::error('Envio Nota Servico not found');

            return redirect(route('envioNotaServicos.index'));
        }

        $this->envioNotaServicoRepository->delete($id);

        Flash::success('Envio Nota Servico deleted successfully.');

        return redirect(route('envioNotaServicos.index'));
    }
}
